#cloud-config
packages:
  - curl
users:
  - name: piwigo
    ssh-authorized-keys:
      - ${master_public_key}
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
  - name: root
    ssh-authorized-keys:
      - ${master_public_key}
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
write_files:
  - path: /root/init-server.sh
    content: |
      ${indent(6, init_server)}
    permissions: "0700"
  - path: /root/docker-compose.yml
    content: |
      ${indent(6, compose_yaml)}
    permissions: "0600"
  - path: /root/run-compose.sh
    content: |
      ${indent(6, run_compose)}
    permissions: "0700"
  - path: /root/run-reboot.sh
    content: |
      ${indent(6, run_reboot)}
    permissions: "0700"
